### ISSUE TITLE
Error under XLF

### ISSUE THREAD

**Issue by pslq** [wrf-model/WRF#676] opened 2018-10-23 08:38 UTC
Compiling em_real under XLF 16.1, is giving the following errors:
-----------------------
ar ru ../main/libwrflib.a module_driver_constants.o module_domain_type.o module_streams.o module_domain.o  module_integrate.o module_timing.o module_configure.o module_tiles.o module_machine.o module_nesting.o module_wrf_error.o module_state_description.o module_sm.o module_io.o module_comm_dm.o module_comm_dm_0.o module_comm_dm_1.o module_comm_dm_2.o module_comm_dm_3.o module_comm_dm_4.o module_comm_nesting_dm.o module_dm.o module_quilt_outbuf_ops.o module_io_quilt.o module_intermediate_nmm.o module_cpl.o module_cpl_oasis3.o module_clear_halos.o wrf_num_bytes_between.o wrf_shutdown.o wrf_debug.o libmassv.o collect_on_comm.o hires_timer.o clog.o nl_get_0_routines.o nl_get_1_routines.o nl_get_2_routines.o nl_get_3_routines.o nl_get_4_routines.o nl_get_5_routines.o nl_get_6_routines.o nl_get_7_routines.o nl_set_0_routines.o nl_set_1_routines.o nl_set_2_routines.o nl_set_3_routines.o nl_set_4_routines.o nl_set_5_routines.o nl_set_6_routines.o nl_set_7_routines.o  module_alloc_space_0.o module_alloc_space_1.o module_alloc_space_2.o module_alloc_space_3.o module_alloc_space_4.o module_alloc_space_5.o module_alloc_space_6.o module_alloc_space_7.o module_alloc_space_8.o module_alloc_space_9.o
ar: creating ../main/libwrflib.a
ar: module_domain_type.o: No such file or directory
make[2]: [framework] Error 1 (ignored)
ranlib ../main/libwrflib.a
ranlib: '../main/libwrflib.a': No such file

[configure.wrf.txt](https://github.com/wrf-model/WRF/files/2505239/configure.wrf.txt)

**Comment by davegill** [comment] 2018-10-23 17:47
@pslq 
Paulo,
As this stands, this is an example that probably a better candidate for the WRF forum. Please go to:
http://forum.mmm.ucar.edu
That forum site is specifically for user support issues. 

Part of the decision process that we use to determine whether something is more appropriate for the forum or the repository issue page:
1. Is this an actual bug in the code? For example, has the xlf compiler found a non-standard usage that the other compilers have been accepting? In this case, we need to see the error issued by the compiler. For a newer user, that is not common knowledge. By going to the forum, a user is in a back-and-forth discussion with WRF User Support, and they will certainly get to the root cause of the problem. If that problem turns out to be a required change for the model source code, the support group typically opens up a source code "issue".

2. On the other hand, is this problem more related to the specific user's computing environment? For example, is OpenMP available, do all of the required libraries exist, how do you access the compiler, are all of the MPI commands in the path, etc. These types of questions are less related to the WRF model source code, and therefore tend to fit better in the forum.

When you post this on the forum, along with your configure.wrf file, please upload the build log. For example, you typed:
```
./compile em_real >& build_log
```
If there are any other important pieces (such as building chemistry, moving nests, etc), please include that information as well.

Later tomorrow, I am going to close this issue.

**Closed** 2018-10-24 14:08 UTC
